#!/bin/bash

## Ecosystems array (aka "ecos")
declare -A ecosystems
ecosystems["--python"]="Python"
ecosystems["--cloud"]="Cloud"
ecosystems["--containers_vm"]="Containers and VMs"
ecosystems["--db_clients"]="Database Clients"
ecosystems["--javascript_node"]="JavaScript and Node"
ecosystems["--web_tools"]="Web Tools"
ecosystems["--java"]="Java"
ecosystems["--c_c++"]="C and C++"
ecosystems["--go"]="Go"
ecosystems["--version_control"]="Version Control"
ecosystems["--php"]="PHP"
ecosystems["--ruby"]="Ruby"
ecosystems["--rust"]="Rust"

check_args() {
    local valid_args=false

    # Check is present and non-empty
    for arg in "$@"; do
        if [ -n "$arg" ] && [ -n "${ecosystems[$arg]}" ]; then
            valid_args=true
            break
        fi
    done

    if [ "$valid_args" = false ]; then
        show_cli_screen
        exit 1
    fi
}

## Provide CLI guidance
show_cli_screen() {
cat << EOF
Welcome. Pass in your ecosystems with options below.

Usage: ./sys --init
       ./sys [ecosystem options]
    

Options:
$(for eco_key in "${!ecosystems[@]}"; do
    echo "  $eco_key"
done)

EOF
}

## Determines OS: Ubuntu, Fedora, Mac, etc
detect_system() {
    if [ -e "/etc/os-release" ]; then
        sys_os=$(awk -F= '/^ID=/{print $2}' /etc/os-release)
    elif [ "$(uname)" == "Darwin" ]; then 
        sys_os="macos"
    fi
}

exec_script() {
    #script="$1"

    # escaped path
    script=$(echo "$1" | sed 's/ /\\ /g')

    log="/tmp/progsys.log"

    #timeout "$timeout_duration" bash "$script" > /dev/null 2>&1

    # probably this one vvv
    #timeout_duration=$((60 * 60))
    #timeout "$timeout_duration" bash -c "$script" > /dev/null 2>&1


    echo "the script: $script"
    #bash -c "$script"
    bash -c "$script" #> /dev/null 2>&1
#    bash -c "$script" 2>&1 >/dev/null | grep -iE '\b(error|fail|exception|already)\b'
    #bash -c "$script" 2>&1 | grep -iE '(error|fail|exception|already)'


    #bash "$script"
    exit_code=$?

    if [[ $exit_code -ne 0 ]]; then
        echo -e "[$(date)] [$exit_code] Failed to run \"$script\"..." >> "$log"
        echo "ERROR. Check "$log
        echo "Attempting to continue..."
    fi

    echo "exit is $exit_code"
    echo "exit is $exit_code"
    echo "exit is $exit_code"
}

install_core_software() {
    local base_directory="$sys_root/$sys_os/_Base_"
    local base_lock_file="/var/run/progsys.lock"
    local base_init_script=$base_directory"/_Init_.sh"

    if [ ! -e "$base_lock_file" ]; then
        exec_script "$base_init_script"

        for script in "$base_directory"/*; do
            if [ $script != "$base_init_script" ]; then
                exec_script "$script"
            fi
        done

        touch "$base_lock_file"
    fi
}

### Main installation logic
install_ecosystems() {
    local selected_flags=("$@")

    mapfile -t lines < "$sys_root/$sys_os/requirements.txt"

    for line in "${lines[@]}"; do
        if [[ $line =~ ^## ]]; then
            current_ecosystem=$(echo "$line" | sed -n 's/## \(.*\) ##/\1/p')
        elif [[ ! "$line" =~ ^[[:space:]]*$ && ! "$line" =~ ^# ]]; then
            for selected_flag in "${!selected_flags[@]}"; do
                flag_key="${selected_flags[$selected_flag]}"
                ecos_key="${ecosystems[$flag_key]}"

                if [ "$current_ecosystem" == "$ecos_key" ]; then
                    echo $line
                   install_ecosystem "$ecos_key" "$line"
                fi
            done
        fi
    done
}

### Install specific ecosystem
install_ecosystem() {
    local eco_key="$1"
    local line="$2"

    if ! [[ $line =~ ^# ]]; then
        santized_line=$(echo "$line" | sed 's/ /_/g')

        script=$(find "$sys_root/$sys_os/$eco_key" -maxdepth 1 -type f -name "???_${santized_line}.sh")

        exec_script "$script"
    fi
}

main() {
    sudo -v # prompt for sudo (unix-like standard)

    check_args "$@"

    detect_system

    export sys_root="/home/$(whoami)/system"

    # called in scripts
    sys_check() {
        local package=$1

        if [ -e "$package" ] && [ -d "$package" ]; then
            return 0
        elif [ -e "$package" ]; then
            return 0
        else
            return 1
        fi
    }
    export -f sys_check

    sys_exec() { . "$sys_root/$1"; }
    export -f sys_exec

    if [[ "$1" == "--init" ]]; then
        install_core_software
    else
        install_ecosystems "$@"
    fi
}


main "$@"
