#!/bin/bash

## Ecosystems array (aka "ecos")
declare -A ecosystems
ecosystems["--python"]="Python"
ecosystems["--cloud"]="Cloud"
ecosystems["--containers_vms"]="Containers and VMs"
ecosystems["--db_clients"]="Database Clients"
ecosystems["--javascript_node"]="JavaScript and Node"
ecosystems["--web_tools"]="Web Tools"
ecosystems["--java"]="Java"
ecosystems["--c_c++"]="C and C++"
ecosystems["--go"]="Go"
ecosystems["--version_control"]="Version Control"
ecosystems["--php"]="PHP"
ecosystems["--ruby"]="Ruby"
ecosystems["--rust"]="Rust"

check_args() {
    local valid_args=false

    if [[ "$1" == "--init" ]]; then
        valid_args=true
    fi

    # Check is present and non-empty
    for arg in "$@"; do
        if [ -n "$arg" ] && [ -n "${ecosystems[$arg]}" ]; then
            valid_args=true
            break
        fi
    done

    if [ "$valid_args" = false ]; then
        show_cli_screen
        exit 1
    fi
}

show_cli_screen() {
cat << EOF
Welcome. Pass in your ecosystems with options below.

Usage: ./sys --init
       ./sys [ecosystem options]
    

Options:
$(for eco_key in "${!ecosystems[@]}"; do
    echo "  $eco_key"
done)

EOF
}

## Determines OS: ubuntu, fedora, macos, etc
detect_system() {
    if [ -e "/etc/os-release" ]; then
        sys_os=$(awk -F= '/^ID=/{print $2}' /etc/os-release)
    elif [ "$(uname)" == "Darwin" ]; then 
        sys_os="macos"
    fi
}

exec_script() {
    eco_key="$1"

    # escaped path
    script=$(echo "$2" | sed 's/ /\\ /g')

    echo "[$eco_key] Installing $script..."

    log="/tmp/progsys.log"

    #duration=$((60 * 60))
    #timeout "$duration" bash -c "$script" 2>&1 | tee -a "$log"
    bash -c "$script" 2>&1 | tee -a "$log"

    if [[ $? -ne 0 ]]; then
        echo "ERROR. Check $log for more information"
        echo "Attempting to continue..."
    fi
}

# _Init_.sh
install_core_software() {
    local base_directory="$sys_root/$sys_os/_Base_"
    local base_lock_file="/var/run/progsys.lock"
    local base_init_script=$base_directory"/_Init_.sh"

    if [ ! -e "$base_lock_file" ]; then
        exec_script "Core" "$base_init_script"

        for script in "$base_directory"/*; do
            if [ $script != "$base_init_script" ]; then
                exec_script "Core" "$script"
            fi
        done

        touch "$base_lock_file"
    fi
}

install_ecosystem() {
    local eco_key="$1"
    local line="$2"

    if ! [[ $line =~ ^# ]]; then
        santized_line=$(echo "$line" | sed 's/ /_/g')

        # todo: better ways of match file number
        script=$(find "$sys_root/$sys_os/$eco_key" -maxdepth 1 -type f -name "???_${santized_line}.sh")

        exec_script "$eco_key" "$script"
    fi
}

# main installation logic
install_ecosystems() {
    local selected_flags=("$@")

    mapfile -t lines < "$sys_root/$sys_os/requirements.txt"

    # todo: in need of optimization
    for line in "${lines[@]}"; do
        if [[ $line =~ ^## ]]; then
            current_ecosystem=$(echo "$line" | sed -n 's/## \(.*\) ##/\1/p')
        elif [[ ! "$line" =~ ^[[:space:]]*$ && ! "$line" =~ ^# ]]; then
            for selected_flag in "${!selected_flags[@]}"; do
                flag_key="${selected_flags[$selected_flag]}"
                ecos_key="${ecosystems[$flag_key]}"

                if [ "$current_ecosystem" == "$ecos_key" ]; then
                   install_ecosystem "$ecos_key" "$line"
                fi
            done
        fi
    done
}


main() {
    sudo -v # prompt for sudo (unix-like standard)

    check_args "$@"

    detect_system

    export sys_root="/home/$(whoami)/system"

    # called in the scripts
    sys_check() {
        local package=$1

        if [ -e "$package" ] && [ -d "$package" ]; then
            return 0
        elif [ -e "$package" ]; then
            return 0
        else
            return 1
        fi
    }
    export -f sys_check

    sys_exec() { . "$sys_root/$1"; }
    export -f sys_exec

    if [[ "$1" == "--init" ]]; then
        install_core_software
    else
        install_ecosystems "$@"
    fi
}


main "$@"